(function exposeOntologyData(root) {
    const terms = typeof module === 'object' && module.exports
        ? require('./terms-data.js')
        : root.IT_QUIZ_BASE_TERMS;

    const topicDefinitions = [
        ['software-basics', '코드와 소프트웨어 기초'],
        ['web-ui', '웹 화면과 렌더링'],
        ['app-platforms', '앱 프레임워크와 플랫폼'],
        ['runtime-cli-packages', '실행 환경과 명령어'],
        ['interfaces-network', 'API와 시스템 연결'],
        ['version-control-delivery', 'Git 협업과 배포'],
        ['developer-ai-tools', '개발·AI 코딩 도구'],
        ['product-design', '화면 설계와 사용자 경험'],
        ['backend-cloud-auth', '백엔드·클라우드·인증'],
        ['data-analysis', '파일과 데이터 분석'],
        ['ai-ml-agents', 'AI·머신러닝·에이전트'],
        ['product-building', '아이디어와 제품 만들기'],
    ];

    const topics = topicDefinitions.map(([id, label]) => ({
        id: `topic-${id}`,
        entityType: 'topic',
        label,
    }));

    const termGroups = {
        'topic-software-basics': [
            ['term-tdd', 'TDD(Test-Driven Development, 테스트 주도 개발)'],
            ['term-markup', 'Markup(마크업)'],
            ['term-markup-language', 'Markup language(마크업 언어)'],
            ['term-snippet', 'Snippet(스니펫)'],
            ['term-module', 'Module(모듈)'],
            ['term-i-o', 'I/O'],
            ['term-library', 'Library(라이브러리)'],
            ['term-framework', 'Framework(프레임워크)'],
            ['term-compile', 'Compile(컴파일)'],
            ['term-execution', 'Execution(실행)'],
            ['term-parsing', 'Parsing(파싱)'],
            ['term-object', 'Object(객체)'],
            ['term-refactoring', 'Refactoring(리팩토링)'],
            ['term-token', 'Token(토큰)'],
            ['term-tree', 'Tree(트리)'],
            ['term-hard-coding', 'Hard coding(하드코딩)'],
        ],
        'topic-web-ui': [
            ['term-static-rendering', '정적 렌더링'],
            ['term-client-rendering', '클라이언트 렌더링'],
            ['term-server-side-rendering', '서버사이드 렌더링'],
            ['term-spa', 'SPA(Single Page Application)'],
            ['term-vanilla-js', 'Vanilla JS(바닐라 JS)'],
            ['term-ui', 'UI(User Interface)'],
            ['term-tailwind-css', 'Tailwind CSS'],
            ['term-html', 'HTML'],
            ['term-css', 'CSS'],
            ['term-javascript', 'JavaScript(자바스크립트)'],
            ['term-react', 'React(리액트)'],
            ['term-dom', 'DOM(Document Object Model)'],
            ['term-virtual-dom', 'Virtual DOM'],
            ['term-component', 'Component(컴포넌트)'],
            ['term-reactive-component', 'Reactive Component(리액티브 컴포넌트)'],
            ['term-rendering', 'Rendering(렌더링)'],
            ['term-pwa', 'PWA(Progressive Web App)'],
            ['term-app-jsx', 'App.jsx'],
            ['term-mui', 'MUI(Material UI)'],
            ['term-vite', 'Vite(비트)'],
            ['term-shadcn-ui', 'shadcn/ui'],
        ],
        'topic-app-platforms': [
            ['term-expo', 'Expo(엑스포)'],
            ['term-typescript', 'TypeScript(타입스크립트)'],
            ['term-react-native', 'React Native'],
            ['term-native', 'Native'],
            ['term-flutter', 'Flutter(플러터)'],
            ['term-vue-js', 'Vue.js'],
            ['term-next-js', 'Next.js'],
            ['term-hosting', 'Hosting(호스팅)'],
            ['term-cross-platform-development', '크로스플랫폼 개발'],
            ['term-app-store-deployment', '앱스토어 배포'],
            ['term-electron', 'Electron'],
            ['term-tauri', 'Tauri'],
        ],
        'topic-runtime-cli-packages': [
            ['term-npm', 'npm(node package manager)'],
            ['term-npm-install', 'npm install'],
            ['term-npm-run-dev', 'npm run dev'],
            ['term-npm-run-build', 'npm run build'],
            ['term-async-io', '비동기 I/O 처리'],
            ['term-cli', 'CLI(Command Line Interface)'],
            ['term-powershell', 'PowerShell(파워쉘)'],
            ['term-node-js', 'Node.js'],
            ['term-runtime', 'Runtime(런타임)'],
            ['term-console', 'Console(콘솔)'],
        ],
        'topic-interfaces-network': [
            ['term-json', 'JSON(JavaScript Object Notation)'],
            ['term-interface', 'Interface(인터페이스)'],
            ['term-api', 'API(Application Programming Interface)'],
            ['term-protocol', 'Protocol(프로토콜)'],
            ['term-mcp', 'MCP(Model Context Protocol)'],
            ['term-http', 'HTTP(Hypertext Transfer Protocol)'],
            ['term-cdn', 'CDN(Content Delivery Network)'],
            ['term-sdk', 'SDK(Software Development Kit)'],
            ['term-routing', 'Routing(라우팅)'],
            ['term-client-server-architecture', '클라이언트-서버 구조'],
            ['term-frontend-backend', '프론트엔드 / 백엔드'],
            ['term-public-data-open-api', '공공데이터 Open API'],
        ],
        'topic-version-control-delivery': [
            ['term-vcs', 'VCS(버전 관리 시스템)'],
            ['term-github', 'GitHub'],
            ['term-github-pages', 'GitHub Pages'],
            ['term-github-actions', 'GitHub Actions'],
            ['term-cloudflare-pages', 'Cloudflare Pages'],
            ['term-vercel', 'Vercel'],
            ['term-netlify', 'Netlify'],
            ['term-gitignore', '.gitignore'],
            ['term-commit-cycle', '커밋 사이클'],
            ['term-branch', '브랜치'],
            ['term-fetch', 'Fetch'],
            ['term-merge', 'Merge'],
        ],
        'topic-developer-ai-tools': [
            ['term-selenium', 'Selenium(셀레니움)'],
            ['term-ide', 'IDE(Integrated Development Environment)'],
            ['term-vibe-coding', 'Vibe Coding(바이브코딩)'],
            ['term-claude-code', 'Claude Code'],
            ['term-codex', 'Codex'],
            ['term-visual-studio-code', 'Visual Studio Code'],
            ['term-cmux', 'cmux'],
            ['term-wmux', 'wmux'],
            ['term-antigravity', 'Antigravity'],
            ['term-lovable', 'Lovable'],
            ['term-v0', 'V0'],
            ['term-google-ai-studio', 'Google AI Studio'],
            ['term-playwright', 'Playwright'],
        ],
        'topic-product-design': [
            ['term-high-fidelity-design', 'High-Fidelity Design(하이파이 시안)'],
            ['term-wireframe', 'Wireframe(와이어프레임)'],
            ['term-prototype', 'Prototype(프로토타입)'],
            ['term-ux', 'UX'],
            ['term-figma', 'Figma'],
            ['term-png', 'PNG'],
            ['term-jpg', 'JPG'],
            ['term-claude-design', 'Claude Design'],
            ['term-figma-make', 'Figma Make'],
            ['term-user-testing', '사용자 테스트'],
        ],
        'topic-backend-cloud-auth': [
            ['term-express', 'Express'],
            ['term-authcontroller-js', 'authController.js'],
            ['term-ruby-on-rails', 'Ruby on Rails(줄여서 Rails, 레일스)'],
            ['term-mvc', 'MVC(Model-View-Controller)'],
            ['term-crud', 'CRUD(Create, Read, Update, Delete)'],
            ['term-env', '.env 파일'],
            ['term-firebase', 'Firebase'],
            ['term-supabase', 'Supabase'],
            ['term-authentication', '인증'],
            ['term-google-auth', 'Google Auth'],
        ],
        'topic-data-analysis': [
            ['term-crawling', 'Crawling(크롤링)'],
            ['term-scraping', 'Scraping(스크래핑)'],
            ['term-txt', 'TXT'],
            ['term-markdown', 'Markdown (MD)'],
            ['term-streamlit', 'Streamlit'],
            ['term-pdf', 'PDF'],
            ['term-python', 'Python'],
            ['term-numpy', 'NumPy'],
            ['term-pandas', 'pandas'],
            ['term-csv', 'CSV'],
            ['term-xlsx', 'XLSX (엑셀)'],
            ['term-jupyter-notebook', 'Jupyter Notebook (.ipynb)'],
            ['term-matplotlib', 'Matplotlib'],
            ['term-plotly', 'Plotly'],
            ['term-data-analysis', '데이터 분석'],
            ['term-rss', 'RSS'],
            ['term-kaggle', '캐글'],
            ['term-eda', 'EDA'],
        ],
        'topic-ai-ml-agents': [
            ['term-generative-ai', '생성형 AI'],
            ['term-gpt', 'GPT'],
            ['term-prompt-engineering', '프롬프트 엔지니어링'],
            ['term-machine-learning', '머신러닝'],
            ['term-tensorflow', 'TensorFlow'],
            ['term-pytorch', 'PyTorch'],
            ['term-deep-learning', '딥러닝'],
            ['term-llm', 'LLM'],
            ['term-context-window', '컨텍스트 윈도우'],
            ['term-ai-agent', 'AI Agent'],
            ['term-subagent', '서브에이전트'],
            ['term-rag', 'RAG'],
            ['term-vector-db', '벡터DB'],
            ['term-tool-calling', 'Tool Calling'],
            ['term-multimodal', '멀티모달'],
            ['term-langchain', 'LangChain'],
            ['term-notion-mcp', 'Notion MCP'],
        ],
        'topic-product-building': [
            ['term-portfolio', '포트폴리오'],
            ['term-team-building', '팀 빌딩'],
            ['term-landing-page', '랜딩페이지'],
            ['term-lean-startup', '린 스타트업'],
            ['term-business-model-canvas', '비즈니스 모델 캔버스'],
            ['term-persona', '페르소나'],
            ['term-mvp', 'MVP'],
            ['term-capstone', '캡스톤'],
            ['term-hackathon', '해커톤'],
        ],
    };

    const assignmentByLabel = new Map();
    const assignedIds = new Set();
    for (const [topicId, assignments] of Object.entries(termGroups)) {
        for (const [id, label] of assignments) {
            if (assignmentByLabel.has(label)) throw new Error(`Duplicate ontology term label: ${label}`);
            if (assignedIds.has(id)) throw new Error(`Duplicate ontology term ID: ${id}`);
            assignmentByLabel.set(label, { id, topicIds: [topicId] });
            assignedIds.add(id);
        }
    }

    const TERM_KINDS = Object.freeze({
        'term-tdd': 'method',
        'term-authcontroller-js': 'file',
        'term-markup': 'concept',
        'term-markup-language': 'concept',
        'term-vcs': 'concept',
        'term-high-fidelity-design': 'concept',
        'term-selenium': 'tool',
        'term-static-rendering': 'method',
        'term-client-rendering': 'method',
        'term-server-side-rendering': 'method',
        'term-spa': 'concept',
        'term-vanilla-js': 'concept',
        'term-snippet': 'concept',
        'term-expo': 'platform',
        'term-module': 'concept',
        'term-json': 'format',
        'term-npm': 'tool',
        'term-npm-install': 'command',
        'term-npm-run-dev': 'command',
        'term-npm-run-build': 'command',
        'term-i-o': 'concept',
        'term-async-io': 'method',
        'term-typescript': 'language',
        'term-cli': 'concept',
        'term-powershell': 'tool',
        'term-interface': 'concept',
        'term-ui': 'concept',
        'term-api': 'concept',
        'term-protocol': 'concept',
        'term-mcp': 'concept',
        'term-ide': 'concept',
        'term-vibe-coding': 'method',
        'term-library': 'concept',
        'term-framework': 'concept',
        'term-ruby-on-rails': 'framework',
        'term-express': 'framework',
        'term-mvc': 'concept',
        'term-react-native': 'framework',
        'term-native': 'method',
        'term-flutter': 'framework',
        'term-vue-js': 'framework',
        'term-tailwind-css': 'framework',
        'term-html': 'language',
        'term-css': 'language',
        'term-javascript': 'language',
        'term-react': 'framework',
        'term-next-js': 'framework',
        'term-dom': 'concept',
        'term-virtual-dom': 'concept',
        'term-component': 'concept',
        'term-reactive-component': 'concept',
        'term-node-js': 'platform',
        'term-runtime': 'concept',
        'term-rendering': 'process',
        'term-routing': 'process',
        'term-wireframe': 'concept',
        'term-prototype': 'concept',
        'term-compile': 'process',
        'term-execution': 'process',
        'term-hosting': 'service',
        'term-parsing': 'process',
        'term-crawling': 'process',
        'term-scraping': 'process',
        'term-object': 'concept',
        'term-refactoring': 'process',
        'term-token': 'concept',
        'term-tree': 'concept',
        'term-http': 'concept',
        'term-cdn': 'service',
        'term-pwa': 'concept',
        'term-sdk': 'concept',
        'term-crud': 'concept',
        'term-app-jsx': 'file',
        'term-mui': 'framework',
        'term-hard-coding': 'method',
        'term-vite': 'tool',
        'term-console': 'tool',
        'term-portfolio': 'concept',
        'term-team-building': 'process',
        'term-generative-ai': 'concept',
        'term-gpt': 'concept',
        'term-prompt-engineering': 'method',
        'term-github': 'service',
        'term-github-pages': 'service',
        'term-github-actions': 'service',
        'term-cloudflare-pages': 'service',
        'term-vercel': 'platform',
        'term-netlify': 'platform',
        'term-cross-platform-development': 'method',
        'term-app-store-deployment': 'process',
        'term-txt': 'format',
        'term-markdown': 'format',
        'term-env': 'file',
        'term-gitignore': 'file',
        'term-shadcn-ui': 'framework',
        'term-claude-code': 'tool',
        'term-codex': 'tool',
        'term-visual-studio-code': 'tool',
        'term-cmux': 'tool',
        'term-wmux': 'tool',
        'term-antigravity': 'tool',
        'term-streamlit': 'framework',
        'term-electron': 'framework',
        'term-tauri': 'framework',
        'term-commit-cycle': 'process',
        'term-branch': 'concept',
        'term-fetch': 'command',
        'term-merge': 'command',
        'term-ux': 'concept',
        'term-figma': 'tool',
        'term-png': 'format',
        'term-jpg': 'format',
        'term-claude-design': 'tool',
        'term-figma-make': 'tool',
        'term-user-testing': 'method',
        'term-landing-page': 'concept',
        'term-lovable': 'tool',
        'term-v0': 'tool',
        'term-google-ai-studio': 'tool',
        'term-firebase': 'platform',
        'term-supabase': 'platform',
        'term-authentication': 'process',
        'term-client-server-architecture': 'concept',
        'term-frontend-backend': 'concept',
        'term-lean-startup': 'method',
        'term-business-model-canvas': 'method',
        'term-persona': 'concept',
        'term-google-auth': 'method',
        'term-pdf': 'format',
        'term-python': 'language',
        'term-numpy': 'framework',
        'term-pandas': 'framework',
        'term-csv': 'format',
        'term-xlsx': 'format',
        'term-jupyter-notebook': 'format',
        'term-matplotlib': 'framework',
        'term-plotly': 'framework',
        'term-data-analysis': 'process',
        'term-machine-learning': 'method',
        'term-tensorflow': 'framework',
        'term-pytorch': 'framework',
        'term-playwright': 'tool',
        'term-rss': 'format',
        'term-public-data-open-api': 'service',
        'term-kaggle': 'platform',
        'term-deep-learning': 'method',
        'term-eda': 'process',
        'term-llm': 'concept',
        'term-context-window': 'concept',
        'term-ai-agent': 'concept',
        'term-subagent': 'concept',
        'term-rag': 'method',
        'term-vector-db': 'concept',
        'term-tool-calling': 'method',
        'term-multimodal': 'concept',
        'term-langchain': 'framework',
        'term-notion-mcp': 'service',
        'term-mvp': 'concept',
        'term-capstone': 'concept',
        'term-hackathon': 'event',
    });

    const termRegistry = terms.map(({ term: label }) => {
        const assignment = assignmentByLabel.get(label);
        if (!assignment) throw new Error(`Missing ontology topic assignment: ${label}`);
        const termKind = TERM_KINDS[assignment.id];
        if (!termKind) throw new Error(`Missing termKind for ontology term: ${assignment.id}`);
        return {
            id: assignment.id,
            entityType: 'term',
            label,
            termKind,
            topicIds: assignment.topicIds,
        };
    });
    if (assignmentByLabel.size !== termRegistry.length) {
        throw new Error('Ontology topic assignments contain labels outside terms-data.js');
    }

    const labelById = new Map(termRegistry.map(item => [item.id, item.label]));
    const sourceByLabel = new Map(terms.map(item => [item.term, item]));
    const weakRationales = {
        'term-tdd': '테스트 방법론인 TDD는 개발 환경과 명령어 경로의 핵심 목표가 아니지만, A안의 전체 커버리지를 위해 약한 배치로 남깁니다.',
        'term-selenium': '브라우저 자동화 도구인 Selenium은 AI 코딩 도구가 아니지만, 독립 QA 경로가 없어 약한 배치로 남깁니다.',
        'term-playwright': '브라우저 자동화 도구인 Playwright는 AI 코딩 도구가 아니지만, 독립 QA 경로가 없어 약한 배치로 남깁니다.',
    };

    function makePath({
        slug, title, description, topicIds, primaryTermIds, supportingTerms,
    }) {
        const supportingTermIds = supportingTerms.map(([termId]) => termId);
        const fitEntries = [
            ...primaryTermIds.map(termId => [termId, 'strong', '']),
            ...supportingTerms,
        ];
        const fitAssessments = Object.fromEntries(fitEntries.map(([termId, fit, explicitRationale]) => {
            if (!labelById.has(termId)) throw new Error(`Unknown learning path term: ${termId}`);
            let fitRationale;
            if (explicitRationale) {
                fitRationale = explicitRationale;
            } else if (fit === 'weak') {
                fitRationale = weakRationales[termId];
            } else {
                const source = sourceByLabel.get(labelById.get(termId));
                const definition = String(source && source.definition || '').replace(/\s+/g, ' ').trim();
                const definitionSummary = definition.length > 90 ? `${definition.slice(0, 89)}…` : definition;
                const role = fit === 'moderate'
                    ? '직접 단계는 아니지만 전제 또는 인접 개념을 구분하는 데'
                    : '핵심 작업 또는 결과를 이해하는 데 직접';
                fitRationale = `${labelById.get(termId)}: 정본 정의의 “${definitionSummary}” 역할이 "${title}" 목표에서 ${role} 필요합니다.`;
            }
            return [termId, { fit, fitRationale }];
        }));
        return {
            id: `path-${slug}`,
            entityType: 'learningPath',
            title,
            description,
            topicIds,
            primaryTermIds,
            supportingTermIds,
            fitAssessments,
            relationIds: [],
            quizTermIds: [...primaryTermIds],
        };
    }

    const learningPaths = [
        makePath({
            slug: 'web-page-basics',
            title: '웹페이지의 구조와 동작 이해하기',
            description: '문서 구조와 스타일, 브라우저 동작, 컴포넌트 구성을 한 흐름으로 익힙니다.',
            topicIds: ['topic-software-basics', 'topic-web-ui'],
            primaryTermIds: [
                'term-markup', 'term-markup-language', 'term-vanilla-js', 'term-html',
                'term-css', 'term-javascript', 'term-react', 'term-component',
            ],
            supportingTerms: [
                ['term-module', 'moderate'], ['term-ui', 'strong'],
                ['term-library', 'moderate'], ['term-tailwind-css', 'moderate'],
                ['term-object', 'moderate'],
            ],
        }),
        makePath({
            slug: 'web-rendering',
            title: '브라우저가 화면을 그리는 방법',
            description: '브라우저 렌더링 방식과 화면 갱신 구조의 차이를 익힙니다.',
            topicIds: ['topic-web-ui', 'topic-interfaces-network'],
            primaryTermIds: [
                'term-rendering', 'term-static-rendering', 'term-client-rendering',
                'term-server-side-rendering', 'term-spa', 'term-dom',
            ],
            supportingTerms: [
                ['term-virtual-dom', 'moderate'], ['term-reactive-component', 'moderate'],
                ['term-pwa', 'moderate'],
            ],
        }),
        makePath({
            slug: 'app-framework-choice',
            title: '앱 개발 방식 선택하기',
            description: '언어와 프레임워크, 실행 플랫폼, 배포 대상을 비교해 앱 개발 방식을 선택합니다.',
            topicIds: ['topic-software-basics', 'topic-web-ui', 'topic-app-platforms'],
            primaryTermIds: [
                'term-framework', 'term-expo', 'term-typescript', 'term-react-native',
                'term-flutter', 'term-vue-js', 'term-electron', 'term-tauri',
                'term-cross-platform-development',
            ],
            supportingTerms: [
                ['term-native', 'moderate'], ['term-app-jsx', 'strong'],
                ['term-app-store-deployment', 'moderate'],
            ],
        }),
        makePath({
            slug: 'runtime-and-commands',
            title: '개발 환경과 명령어 사용하기',
            description: '프로그램의 실행 환경과 패키지 설치, 개발·빌드 명령의 역할을 익힙니다.',
            topicIds: ['topic-software-basics', 'topic-runtime-cli-packages', 'topic-web-ui'],
            primaryTermIds: [
                'term-npm', 'term-npm-install', 'term-npm-run-dev', 'term-npm-run-build',
                'term-async-io', 'term-cli', 'term-node-js', 'term-runtime',
                'term-vite', 'term-console',
            ],
            supportingTerms: [
                ['term-tdd', 'weak'], ['term-i-o', 'moderate'],
                ['term-powershell', 'strong'], ['term-compile', 'strong'],
                ['term-execution', 'strong'],
            ],
        }),
        makePath({
            slug: 'api-system-connection',
            title: 'API로 시스템 연결하기',
            description: '클라이언트와 서버가 규약과 데이터 형식을 통해 정보를 주고받는 구조를 익힙니다.',
            topicIds: ['topic-interfaces-network'],
            primaryTermIds: [
                'term-interface', 'term-api', 'term-protocol', 'term-http',
                'term-json', 'term-client-server-architecture', 'term-public-data-open-api',
            ],
            supportingTerms: [
                ['term-sdk', 'moderate'], ['term-frontend-backend', 'moderate'],
                [
                    'term-routing',
                    'moderate',
                    'Routing은 네트워크 트래픽이 목적지까지 이동할 경로를 정하는 개념이므로 API와 시스템 연결 경로에서 통신 흐름을 이해하는 데 필요합니다.',
                ],
            ],
        }),
        makePath({
            slug: 'git-collaboration',
            title: 'Git으로 변경 이력과 협업 관리하기',
            description: '저장소의 변경 이력을 안전하게 나누고 합치는 기본 협업 흐름을 익힙니다.',
            topicIds: ['topic-version-control-delivery'],
            primaryTermIds: [
                'term-vcs', 'term-github', 'term-github-actions', 'term-gitignore',
                'term-commit-cycle', 'term-branch', 'term-fetch', 'term-merge',
            ],
            supportingTerms: [],
        }),
        makePath({
            slug: 'web-deployment',
            title: '웹 앱이 배포되기까지',
            description: '웹 화면을 작성하고 빌드한 뒤 자동화된 배포 서비스에 공개하는 순서를 익힙니다.',
            topicIds: [
                'topic-web-ui', 'topic-app-platforms',
                'topic-interfaces-network', 'topic-version-control-delivery',
            ],
            primaryTermIds: [
                'term-html', 'term-css', 'term-javascript', 'term-react',
                'term-vite', 'term-github', 'term-github-actions', 'term-github-pages',
            ],
            supportingTerms: [
                ['term-next-js', 'strong'], ['term-hosting', 'strong'],
                ['term-cdn', 'strong'], ['term-pwa', 'moderate'],
                ['term-cloudflare-pages', 'strong'], ['term-vercel', 'strong'],
                ['term-netlify', 'strong'],
            ],
        }),
        makePath({
            slug: 'ai-coding-tools',
            title: 'AI 코딩 도구와 개발 환경 사용하기',
            description: '코딩 환경과 AI 보조 도구의 역할을 구분하고 작업에 맞게 선택합니다.',
            topicIds: ['topic-software-basics', 'topic-developer-ai-tools'],
            primaryTermIds: [
                'term-ide', 'term-vibe-coding', 'term-claude-code', 'term-codex',
                'term-visual-studio-code', 'term-cmux', 'term-wmux', 'term-antigravity',
                'term-lovable', 'term-google-ai-studio',
            ],
            supportingTerms: [
                ['term-selenium', 'weak'], ['term-playwright', 'weak'],
                ['term-snippet', 'moderate'], ['term-refactoring', 'moderate'],
                ['term-hard-coding', 'moderate'],
            ],
        }),
        makePath({
            slug: 'interface-design',
            title: '화면을 설계하고 사용자에게 검증하기',
            description: '초기 구조에서 시각 시안과 사용자 검증까지 화면 설계 산출물을 연결합니다.',
            topicIds: ['topic-web-ui', 'topic-developer-ai-tools', 'topic-product-design'],
            primaryTermIds: [
                'term-high-fidelity-design', 'term-ui', 'term-tailwind-css',
                'term-wireframe', 'term-prototype', 'term-mui', 'term-ux',
                'term-figma', 'term-shadcn-ui', 'term-user-testing',
            ],
            supportingTerms: [
                ['term-png', 'moderate'], ['term-jpg', 'moderate'],
                ['term-claude-design', 'moderate'], ['term-figma-make', 'moderate'],
                ['term-v0', 'moderate'],
            ],
        }),
        makePath({
            slug: 'backend-cloud-auth',
            title: '백엔드·클라우드·인증 구성하기',
            description: '서버 코드 구조, 데이터 작업, 환경 설정과 로그인 구성을 함께 익힙니다.',
            topicIds: ['topic-backend-cloud-auth'],
            primaryTermIds: [
                'term-express', 'term-authcontroller-js', 'term-ruby-on-rails', 'term-mvc',
                'term-crud', 'term-env', 'term-firebase', 'term-supabase',
                'term-authentication', 'term-google-auth',
            ],
            supportingTerms: [],
        }),
        makePath({
            slug: 'data-files',
            title: '데이터 파일을 읽고 변환하기',
            description: '여러 파일 형식과 수집·해석 과정을 구분해 데이터를 변환하는 기초를 익힙니다.',
            topicIds: ['topic-software-basics', 'topic-data-analysis'],
            primaryTermIds: [
                'term-txt', 'term-markdown', 'term-scraping',
                'term-pdf', 'term-csv', 'term-xlsx',
            ],
            supportingTerms: [
                ['term-parsing', 'moderate'], ['term-crawling', 'moderate'],
                ['term-tree', 'moderate'], ['term-rss', 'moderate'],
            ],
        }),
        makePath({
            slug: 'data-analysis',
            title: 'Python으로 데이터를 분석하기',
            description: 'Python 도구로 데이터를 탐색하고 표와 시각화 결과를 만드는 흐름을 익힙니다.',
            topicIds: ['topic-data-analysis'],
            primaryTermIds: [
                'term-python', 'term-numpy', 'term-pandas', 'term-jupyter-notebook',
                'term-matplotlib', 'term-plotly', 'term-data-analysis', 'term-eda',
                'term-streamlit',
            ],
            supportingTerms: [],
        }),
        makePath({
            slug: 'machine-learning',
            title: '머신러닝 모델을 이해하기',
            description: '데이터 분석에서 머신러닝과 딥러닝 도구로 이어지는 기본 개념을 익힙니다.',
            topicIds: ['topic-data-analysis', 'topic-ai-ml-agents'],
            primaryTermIds: [
                'term-python', 'term-data-analysis', 'term-machine-learning',
                'term-tensorflow', 'term-pytorch', 'term-kaggle',
                'term-deep-learning', 'term-eda',
            ],
            supportingTerms: [
                ['term-numpy', 'moderate'], ['term-pandas', 'moderate'],
                ['term-jupyter-notebook', 'moderate'],
            ],
        }),
        makePath({
            slug: 'llm-agents',
            title: 'LLM이 정보와 도구를 사용하는 방법',
            description: '언어 모델이 문맥과 검색 정보, 외부 도구를 사용해 작업하는 구조를 익힙니다.',
            topicIds: ['topic-software-basics', 'topic-interfaces-network', 'topic-ai-ml-agents'],
            primaryTermIds: [
                'term-generative-ai', 'term-gpt', 'term-prompt-engineering',
                'term-mcp', 'term-llm', 'term-context-window', 'term-ai-agent',
                'term-rag', 'term-tool-calling', 'term-multimodal',
            ],
            supportingTerms: [
                ['term-token', 'moderate'], ['term-subagent', 'strong'],
                ['term-vector-db', 'strong'], ['term-langchain', 'strong'],
                ['term-notion-mcp', 'strong'],
            ],
        }),
        makePath({
            slug: 'product-building',
            title: '아이디어를 제품과 포트폴리오로 만들기',
            description: '고객 가설을 검증하고 최소 제품과 결과물을 만드는 사업 흐름을 익힙니다.',
            topicIds: ['topic-product-building'],
            primaryTermIds: [
                'term-portfolio', 'term-team-building', 'term-landing-page',
                'term-lean-startup', 'term-business-model-canvas', 'term-persona',
                'term-mvp', 'term-capstone', 'term-hackathon',
            ],
            supportingTerms: [],
        }),
    ];

    const relations = [
        {
            id: "rel-authcontroller-js-runs-on-node-js",
            source: "term-authcontroller-js",
            target: "term-node-js",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "authController.js는 Node.js(Express) 기반 프로젝트에서 인증 로직을 담당하는 파일입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-authcontroller-js" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-authcontroller-js-runs-on-node-js-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-electron-runs-on-javascript",
            source: "term-electron",
            target: "term-javascript",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "Electron은 HTML·CSS·JavaScript 웹 기술로 데스크톱 앱을 만듭니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-electron" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-electron-runs-on-javascript-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-expo-runs-on-react-native",
            source: "term-expo",
            target: "term-react-native",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "Expo는 React Native 위에 구축된 플랫폼입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-expo" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-expo-runs-on-react-native-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-figma-make-part-of-figma",
            source: "term-figma-make",
            target: "term-figma",
            type: "part_of",
            status: "REVIEWED",
            rationale: "Figma Make는 Figma 안에서 동작하는 기능이므로 결과물 생성이 아니라 구성 관계입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-figma-make" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-figma-make-part-of-figma-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-markdown-is-a-markup-language",
            source: "term-markdown",
            target: "term-markup-language",
            type: "is_a",
            status: "REVIEWED",
            rationale: "Markdown은 마크업 언어의 대표 사례로 정의문에 제시됩니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-markup-language" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-markdown-is-a-markup-language-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-matplotlib-runs-on-python",
            source: "term-matplotlib",
            target: "term-python",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "Matplotlib은 Python 시각화 라이브러리입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-matplotlib" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-matplotlib-runs-on-python-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-mui-runs-on-react",
            source: "term-mui",
            target: "term-react",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "MUI는 React 기반의 UI 컴포넌트 라이브러리입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-mui" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-mui-runs-on-react-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-react-native-used-with-javascript",
            source: "term-react-native",
            target: "term-javascript",
            type: "used_with",
            status: "REVIEWED",
            rationale: "React Native는 JavaScript와 React를 사용해 모바일 앱을 개발합니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-react-native" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-react-native-used-with-javascript-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-react-runs-on-javascript",
            source: "term-react",
            target: "term-javascript",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "React는 JavaScript 기반 라이브러리입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-react" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-react-runs-on-javascript-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-ruby-on-rails-implements-mvc",
            source: "term-ruby-on-rails",
            target: "term-mvc",
            type: "implements",
            status: "REVIEWED",
            rationale: "Ruby on Rails는 MVC 아키텍처를 따르는 웹 애플리케이션 프레임워크입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-ruby-on-rails" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-ruby-on-rails-implements-mvc-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-server-side-rendering-produces-html",
            source: "term-server-side-rendering",
            target: "term-html",
            type: "produces",
            status: "REVIEWED",
            rationale: "서버사이드 렌더링은 서버가 요청에 맞는 HTML을 생성해 브라우저에 전달합니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-server-side-rendering" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-server-side-rendering-produces-html-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-shadcn-ui-runs-on-react",
            source: "term-shadcn-ui",
            target: "term-react",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "shadcn/ui는 React 기반 구성요소 모음입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-shadcn-ui" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-shadcn-ui-runs-on-react-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-static-rendering-produces-html",
            source: "term-static-rendering",
            target: "term-html",
            type: "produces",
            status: "REVIEWED",
            rationale: "정적 렌더링은 빌드 시점에 페이지 내용을 미리 HTML로 생성합니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-static-rendering" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-static-rendering-produces-html-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-streamlit-runs-on-python",
            source: "term-streamlit",
            target: "term-python",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "Streamlit은 Python 코드만으로 데이터·인공지능 웹앱을 만드는 프레임워크입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-streamlit" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-streamlit-runs-on-python-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-tailwind-css-runs-on-css",
            source: "term-tailwind-css",
            target: "term-css",
            type: "runs_on",
            status: "REVIEWED",
            rationale: "Tailwind CSS는 유틸리티 클래스 기반의 CSS 프레임워크입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-tailwind-css" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-tailwind-css-runs-on-css-20260905",
            reviewedAt: "2026-09-05",
        },
        {
            id: "rel-vite-used-with-react",
            source: "term-vite",
            target: "term-react",
            type: "used_with",
            status: "REVIEWED",
            rationale: "Vite는 React를 포함한 프론트엔드 프레임워크와 함께 사용하는 빌드 도구입니다.",
            sourceRefs: [{ kind: "term-definition", ref: "term-vite" }],
            reviewedByRole: "content-owner",
            reviewRecordId: "review-rel-vite-used-with-react-20260905",
            reviewedAt: "2026-09-05",
        },
    ];

    const ontology = { topics, termRegistry, relations, learningPaths };
    root.IT_QUIZ_ONTOLOGY = ontology;
    if (typeof module === 'object' && module.exports) module.exports = ontology;
})(typeof globalThis !== 'undefined' ? globalThis : window);
